# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/bhayame/Desktop/Lab 7/Lab 7.cache/wt} [current_project]
set_property parent.project_path {C:/Users/bhayame/Desktop/Lab 7/Lab 7.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/bhayame/Desktop/Lab 7/Lab 7.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/imports/new/mux2to1.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/imports/new/countUD5L.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/countU5.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/GapStateMachineLogic.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/GapSize.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/countUD10L.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/countU10.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/FlashModule.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/SlugRedDetect.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/GapWallDetect.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/GapStateMachine.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/GapVerticalComponent.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/GapHorizontalComponent.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/imports/new/EdgeDetector.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/TopStateMachineLogic.v}
  C:/Users/bhayame/Desktop/TIMER/TIMER.srcs/sources_1/new/secondTicker.v
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/imports/new/m8_1e.v}
  C:/Users/bhayame/Desktop/TIMER/TIMER.srcs/sources_1/new/countU4.v
  C:/Users/bhayame/Desktop/TIMER/TIMER.srcs/sources_1/new/countU3.v
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/HorizGap7.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/HorizGap6.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/HorizGap5.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/HorizGap4.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/HorizGap2.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/HorizGap3.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/HorizGap1.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/H7.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/H6.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/H5.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/H4.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/H3.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/H2.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/H1.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VertGap7.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VertGap6.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VertGap5.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VertGap4.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VertGap3.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VertGap2.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VertGap1.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/BGCollisionDetector.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/V7.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/V6.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/V4.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/SlugPositionSet.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/V5.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/V3.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/btnChecker.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/SlugVerticalComponent.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/SlugHorizontalComponent.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VerticalCounter.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/HorizontalCounter.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/V2.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/V1.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/WinDetector.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/TopStateMachine.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/LossDetector.v}
  C:/Users/bhayame/Desktop/TIMER/TIMER.srcs/sources_1/new/Timer.v
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/imports/Desktop/Lab 4/Lab 4.srcs/sources_1/new/Selector.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/imports/Desktop/Lab 4/Lab 4.srcs/sources_1/new/RingCounter.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/imports/Desktop/Lab 4/Lab 4.srcs/sources_1/new/hex7seg.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/qsecTicker.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/HorizontalObstacles.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/HorizontalGaps.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VerticalGaps.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VerticalObstacles.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/SlugGenerator.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/BorderGenerator.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/imports/Downloads/lab7_clks.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/VGAController.v}
  {C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/sources_1/new/TopLevel.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/bhayame/Desktop/Lab 7/Lab 7.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc}}]


synth_design -top TopLevel -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TopLevel.dcp

catch { report_utilization -file TopLevel_utilization_synth.rpt -pb TopLevel_utilization_synth.pb }
